FROM ubuntu:20.04 as builder
ARG VERSION

ENV BWA_URL=https://github.com/lh3/bwa/releases/download/v$VERSION/bwa-$VERSION.tar.bz2

RUN apt-get update \
    && apt-get install -y \
       bzip2 \
       gcc \
       libbz2-dev \
       liblzma-dev \
       libncurses5-dev \
       make \
       wget \
       zlib1g-dev \
    && wget -O bwa.tar.bz2 $BWA_URL \
    && tar xf bwa.tar.bz2 \
    && cd bwa-$VERSION \
    && make -j $(nproc) \
    && mv bwa /usr/local/bin/

COPY --from=ghcr.io/martinluttap/samtools:1.8 /samtools-1.8.tar.bz2 /
RUN cd / \
	&& tar xf samtools-1.8.tar.bz2 \
    && cd samtools-1.8 \
    && ./configure --prefix=/usr/local \
    && make -j $(nproc) \
    && make install -j $(nproc) \
    && cd ../ \
    && rm -rf samtools-1.8 \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*